spring:
  config:
    import: "optional:file:.env[.properties]"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop # test!!!!
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
jwt:
  issuer: ${JWT_ISSUER}
  secret_key: ${JWT_SECRET_KEY}
