name: Java CI with Gradle

# Run on push or pull request to the main branch
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy: 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    # Set up JDK 17 (needed for Spring Boot 3.0.2)
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    # Spring Boot application build (1)
    - name: Spring Boot Build
      run: ./gradlew clean build --exclude-task test
    
    # Docker image build (2)
    - name: Docker image build
      run: docker build -t sumsum07/capmap-app .
    
    # DockerHub login (3)
    - name: Docker login 
      uses: docker/login-action@v2
      with: 
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Docker Hub push (4)
    - name: Docker Hub push
      run: docker push lucaskang134/boot-prac-ci
